#sp11-zuul
spring:
  application:
    name: zuul
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  retryable: true

#  routes:       #zuul 路由配置可以省略，缺省以服务 id 作为访问路径
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**
    
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
hystrix:    #设置超时时间，降低 hystrix 超时时间，以便测试降级
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
            
management:   #暴露 hystrix.stream 监控端点
  endpoints:
    web:
      exposure:
        include: hystrix.stream